import Link from 'next/link'
import { Mail, Send, MessageCircle, ArrowUpRight, Code2 } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { site } from '@/lib/site'

export default function Contact(){
  return <section className="container py-10 md:py-16"><div data-aos="modern-up" className="relative overflow-hidden rounded-[2rem] border bg-card p-6 shadow-2xl shadow-primary/5 md:p-10 soft-grid"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-primary/20 blur-3xl"/><div className="relative max-w-2xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border bg-background/80 px-4 py-2 text-sm font-bold"><MessageCircle className="h-4 w-4 text-primary"/> Contact</div><h1 className="break-words text-4xl md:text-6xl">{site.contact.title}</h1><p className="mt-4 leading-8 text-muted-foreground">{site.contact.description}</p></div></div><div className="mt-8 grid gap-5 md:grid-cols-3"><Card data-aos="modern-up" className="modern-card"><CardHeader><Mail className="mb-3 h-8 w-8 text-primary"/><CardTitle>Email</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">Kirim laporan bug atau request endpoint.</p><Button asChild className="rounded-full"><Link href={`mailto:${site.contact.email}`}><Mail className="h-4 w-4"/>{site.contact.email}</Link></Button></CardContent></Card><Card data-aos="modern-up" data-aos-delay="70" className="modern-card"><CardHeader><Send className="mb-3 h-8 w-8 text-primary"/><CardTitle>Telegram</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">Hubungi developer lewat Telegram.</p><Button asChild variant="outline" className="rounded-full"><Link href={site.contact.telegram}><ArrowUpRight className="h-4 w-4"/>Open Telegram</Link></Button></CardContent></Card><Card data-aos="modern-up" data-aos-delay="140" className="modern-card"><CardHeader><Code2 className="mb-3 h-8 w-8 text-primary"/><CardTitle>GitHub</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">Lihat profil developer dan project publik.</p><Button asChild variant="outline" className="rounded-full"><Link href={site.contact.github}><ArrowUpRight className="h-4 w-4"/>Open GitHub</Link></Button></CardContent></Card></div></section>
}
