import Link from 'next/link'
import { Boxes, LayoutGrid, Route, ArrowRight } from 'lucide-react'
import { categories, plugins } from '@/lib/generated-plugins'
import { Card, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { titleCase } from '@/lib/utils'

export default function Browse(){
  return <section className="container py-10 md:py-16"><div data-aos="modern-up" className="relative overflow-hidden rounded-[2rem] border bg-card p-6 shadow-2xl shadow-primary/5 md:p-10 soft-grid"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-primary/20 blur-3xl"/><div className="relative"><div className="mb-4 inline-flex items-center gap-2 rounded-full border bg-background/80 px-4 py-2 text-sm font-bold"><LayoutGrid className="h-4 w-4 text-primary"/> Browse Module</div><h1 className="break-words text-4xl md:text-6xl">Semua Kategori API</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">Pilih module yang tersedia untuk melihat endpoint REST API publik di dalamnya.</p></div></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{categories.map((c,i)=><Link data-aos="modern-up" data-aos-delay={i*60} key={c.slug} href={`/docs/${c.slug}`}><Card className="modern-card group h-full overflow-hidden"><CardHeader><div className="mb-4 flex items-center justify-between"><span className="grid h-14 w-14 place-items-center rounded-3xl bg-primary/10 text-primary transition group-hover:scale-110"><Boxes className="h-7 w-7"/></span><ArrowRight className="h-5 w-5 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-primary"/></div><CardTitle>{titleCase(c.slug)}</CardTitle><CardDescription className="flex items-center gap-2"><Route className="h-4 w-4"/>{c.count} endpoint tersedia</CardDescription></CardHeader></Card></Link>)}</div><div className="mt-8 rounded-3xl border bg-card p-6 text-center text-muted-foreground">Total {plugins.length} endpoint aktif dari {categories.length} module.</div></section>
}
