// Auto generated by scripts/generate-plugins.ts
import plugin0 from '@/lib/plugins/game/cek-kodam'
export const plugins = [plugin0]
export const categories = [
  {
    "slug": "game",
    "title": "Game",
    "icon": "Boxes",
    "count": 1
  }
]
export function findPlugin(category:string, endpoint:string){return plugins.find(p=>p.category===category&&p.slug===endpoint)}
