import fs from 'fs'
import path from 'path'
const root = process.cwd(); const pluginsDir = path.join(root,'lib/plugins');
function titleCase(s:string){return s.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
const imports:string[]=[]; const names:string[]=[]; const cats:Record<string,{slug:string,title:string,icon:string,count:number}>={}; let i=0;
for(const category of fs.readdirSync(pluginsDir)){const cdir=path.join(pluginsDir,category); if(!fs.statSync(cdir).isDirectory()) continue; const files=fs.readdirSync(cdir).filter(f=>f.endsWith('.ts')&&!f.endsWith('.d.ts')); for(const file of files){const name=`plugin${i++}`; const slug=file.replace(/\.ts$/,''); imports.push(`import ${name} from '@/lib/plugins/${category}/${slug}'`); names.push(name); cats[category]??={slug:category,title:titleCase(category),icon:'Boxes',count:0}; cats[category].count++;}}
const out=`// Auto generated by scripts/generate-plugins.ts\n${imports.join('\n')}\nexport const plugins = [${names.join(', ')}]\nexport const categories = ${JSON.stringify(Object.values(cats),null,2)}\nexport function findPlugin(category:string, endpoint:string){return plugins.find(p=>p.category===category&&p.slug===endpoint)}\n`;
fs.writeFileSync(path.join(root,'lib/generated-plugins.ts'),out)
console.log(`Generated ${names.length} plugins`)
